name: Main demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: List files in the repository
        run: java src/p1/P1capstone.java
        
      - name: Run tests on java file
        run: java src/p1/P1capstoneTest.java
